import type { Product, Category } from "@/types"

export const mockCategories: Category[] = [
  { id: "all", name: "All Products", icon: "grid", count: 156 },
  { id: "electronics", name: "Electronics", icon: "smartphone", count: 45 },
  { id: "fashion", name: "Fashion", icon: "shirt", count: 67 },
  { id: "home", name: "Home & Living", icon: "home", count: 23 },
  { id: "beauty", name: "Beauty", icon: "sparkles", count: 21 },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    description:
      "Premium noise-cancelling headphones with 30-hour battery life. Perfect for music lovers and professionals. Features include active noise cancellation, comfortable over-ear design, and crystal clear sound quality.",
    price: 89.99,
    category: "electronics",
    images: ["/black-wireless-headphones.jpg", "/headphones-side-view.png", "/headphones-folded.jpg"],
    colors: ["Black", "Silver", "Rose Gold"],
    types: ["Standard", "Pro"],
    sellerId: "seller1",
    sellerName: "TechZim",
    sellerCompany: "TechZim Electronics",
    inStock: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "2",
    name: "Cotton Summer Dress",
    description:
      "Elegant and comfortable summer dress made from 100% organic cotton. Perfect for any occasion. Available in multiple colors and sizes.",
    price: 45.0,
    category: "fashion",
    images: ["/blue-summer-dress.jpg", "/dress-back-view.jpg"],
    colors: ["Blue", "Pink", "White", "Yellow"],
    sellerId: "seller2",
    sellerName: "Fashion Forward",
    sellerCompany: "Fashion Forward Zim",
    inStock: true,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: "3",
    name: "Smart Watch Pro",
    description:
      "Advanced fitness tracking smartwatch with heart rate monitor, GPS, and 7-day battery life. Water resistant up to 50m.",
    price: 199.99,
    category: "electronics",
    images: ["/black-smartwatch.jpg", "/smartwatch-fitness.png"],
    colors: ["Black", "Space Gray", "Gold"],
    types: ["40mm", "44mm"],
    sellerId: "seller1",
    sellerName: "TechZim",
    sellerCompany: "TechZim Electronics",
    inStock: true,
    rating: 4.9,
    reviews: 203,
  },
  {
    id: "4",
    name: "Handwoven Basket Set",
    description:
      "Beautiful set of 3 handwoven baskets made by local artisans. Perfect for storage or decoration. Supports local communities.",
    price: 35.0,
    category: "home",
    images: ["/woven-baskets-natural.jpg", "/handmade-baskets.jpg"],
    sellerId: "seller3",
    sellerName: "HomeStyle Zim",
    inStock: true,
    rating: 4.7,
    reviews: 56,
  },
  {
    id: "5",
    name: "Natural Shea Butter Cream",
    description:
      "Organic shea butter moisturizer made from locally sourced ingredients. Nourishes and hydrates all skin types.",
    price: 18.5,
    category: "beauty",
    images: ["/shea-butter-cream-jar.jpg"],
    sellerId: "seller4",
    sellerName: "Natural Beauty Zim",
    sellerCompany: "Natural Beauty Co.",
    inStock: true,
    rating: 4.9,
    reviews: 178,
  },
  {
    id: "6",
    name: "Leather Crossbody Bag",
    description:
      "Handcrafted genuine leather crossbody bag with adjustable strap. Perfect size for everyday essentials.",
    price: 65.0,
    category: "fashion",
    images: ["/brown-leather-bag.jpg", "/leather-bag-open.jpg"],
    colors: ["Brown", "Black", "Tan"],
    sellerId: "seller2",
    sellerName: "Fashion Forward",
    sellerCompany: "Fashion Forward Zim",
    inStock: true,
    rating: 4.5,
    reviews: 67,
  },
]
